/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/sobre`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/alertas` | `/alertas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/configuracoes` | `/configuracoes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sensores` | `/sensores`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/sobre`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/alertas` | `/alertas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/configuracoes` | `/configuracoes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sensores` | `/sensores`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/cadastro${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/sobre${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/alertas${`?${string}` | `#${string}` | ''}` | `/alertas${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/configuracoes${`?${string}` | `#${string}` | ''}` | `/configuracoes${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sensores${`?${string}` | `#${string}` | ''}` | `/sensores${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/sobre`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/alertas` | `/alertas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/configuracoes` | `/configuracoes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sensores` | `/sensores`; params?: Router.UnknownInputParams; };
    }
  }
}
